name = "Ripemd"
uuid = "92ef3814-971d-54d3-b0c1-59b1d13fee15"
authors = ["Guido Kraemer <gdkrmr@users.noreply.github.com>"]
version = "0.3.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
